enum eGameMode {
	GM_NONE = 0,
	GM_CAREER = 1,
	GM_TIME_ATTACK = 2,
	GM_SINGLE_RACE = 3,
	GM_INSTANT_ACTION = 4,
	GM_CRASHTEST_DUMMY = 5,
	GM_ONLINE_MULTIPLAYER = 6,
	GM_PARTY = 7,
	GM_DEVELOPER = 8,
	GM_TOURNAMENT = 9,
	GM_SPLITSCREEN = 10,
	GM_TEST = 11,
};

enum eGameRules {
	GR_DEFAULT = 0,
	GR_RACE = 1,
	GR_STUNT = 2,
	GR_DERBY = 3,
	GR_HUNTER_PREY = 4,
	GR_ARCADE_ADVENTURE = 5,
	GR_PONGRACE = 6,
	GR_TIMEATTACK = 7,
	GR_TEST = 8,
};

enum eStuntType {
	STUNT_NONE = 0,
	STUNT_CURLING = 1,
	STUNT_BULLSEYE = 2,
	STUNT_HIGHJUMP = 3,
	STUNT_STONESKIPPING = 4,
	STUNT_RINGOFFIRE = 5,
	STUNT_DARTS = 6,
	STUNT_BREAKDOWN = 7,
	STUNT_BLACKDANNY = 8,
	STUNT_SKIJUMP = 9,
	STUNT_FIELDGOAL = 10,
	STUNT_BOWLING = 11,
	STUNT_BASKETBALL = 12,
	STUNT_BASEBALL = 13,
	STUNT_SOCCER = 14,
};

enum eCareerClass {
	CLASS_NONE = 0,
	CLASS_C = 1,
	CLASS_B = 2,
	CLASS_A = 3,
	CLASS_FINALS = 4,
	CLASS_EXTRA = 5,
};

enum eDerbyType {
	DERBY_NONE = 0,
	DERBY_LMS = 1,
	DERBY_WRECKING = 2,
	DERBY_FRAG = 3,
};

enum eUpgradeLevel {
	UPGRADE_DEFAULT = 0,
	UPGRADE_NONE = 1,
	UPGRADE_50 = 2,
	UPGRADE_100 = 3,
};

enum ePlayerType {
	PLAYERTYPE_UNKNOWN = 0,
	PLAYERTYPE_LOCAL = 1,
	PLAYERTYPE_REMOTE = 2,
	PLAYERTYPE_OBSERVER = 3,
	PLAYERTYPE_AI = 4,
	PLAYERTYPE_SIMULATED = 5,
};